name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Executar todos os testes locais
      run: npm test

    - name: Subir API REST
      run: nohup npm start &

    - name: Subir API GraphQL
      run: nohup node graphql/server.js &

    - name: Esperar servidores estarem funcionando
      run: sleep 8

    - name: Executar testes externos REST
      run: npm run test-external

    - name: Executar testes externos GraphQL
      run: npm run test-graphql-external
