name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Instalar dependências
      run: npm install

    - name: Executar os testes de API REST via Controller
      run: npm run test-rest-controller

    - name: Executar os testes de API GraphQL via Controller
      run: npm run test-graphql-controller
      
    - name: Subir API REST
      run: npm run start-rest &

    - name: Subir API GraphQL
      run: npm run start-graphql & 

    - name: Esperar servidores estarem funcionando
      run: sleep 8

    - name: Executar testes externos de API REST
      run: npm run test-rest-external

    - name: Executar testes externos de API GraphQL
      run: npm run test-graphql-external
